on:
  push:
    branches:
      - main

name: Build and deploy

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy
        run: sam deploy --stack-name BilibiliDailyUp --s3-bucket lambdaservicebucket --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --parameter-overrides BiliBiliCookiesBase64=${{ secrets.BILIBILI_COOKIES_BASE64 }} PushPlusToken=${{ secrets.PUSHPLUS_TOKEN }} ServerChanToken=${{ secrets.SERVERCHAN_TOKEN }}